### ISSUE TITLE
Add kubectl-graph to krew-index

### ISSUE THREAD

**Issue by ishantanu** [steveteuber/kubectl-graph#1]
Hi 👋 

Maintainer of the [awesome-kubectl-plugins](https://github.com/ishantanu/awesome-kubectl-plugins) here. I recently discovered this kubectl plugin and I was curious if you would like to make this available to a larger userbase via [krew](https://github.com/kubernetes-sigs/krew).

The reference issue for adding this plugin to krew via [krew-index](https://github.com/kubernetes-sigs/krew-index) is https://github.com/kubernetes-sigs/krew-index/issues/503. The plugins added to [krew-index](https://github.com/kubernetes-sigs/krew-index) are available to install via [krew](https://github.com/kubernetes-sigs/krew) CLI.

**Comment by steveteuber** [comment]
Hi @ishantanu,

Thank you for opening the #1 "issue". This repository is not even a week old ;-)
And yes, I would like to make this plugin available via `krew`.

But first I need to create a fully working `kubectl` plugin.
When everything works as expected, then I create a release and add it to the `krew-index`.

**Comment by ishantanu** [comment]
Sure, no problem. Looking forward to trying this plugin when it's ready. 🙂

**Comment by corneliusweig** [comment]
Hey @steveteuber, what's the status on your project? Is it ready for `krew`?

**Comment by steveteuber** [comment]
Hey @corneliusweig,

Thanks for asking. Last weekend I had a first look at `goreleaser` and its working like a sharm.
After the virtual #KubeCon I want to take a look into `krew` so we can finally close the issues #1 and https://github.com/kubernetes-sigs/krew-index/issues/503.

**Comment by jmorcar** [comment]
Hi @steveteuber , How to install/use this plugin without Krew tool? I would like to test your plugin but I don't want install another tool too. Thanks!!

**Comment by steveteuber** [comment]
Hi @jmorcar,

To install this plugin without `krew`, simply download a release and move the executable file `kubectl-graph` to anywhere on your `PATH`. Then you can check if the plugin listed under available plugins:

```
$ kubectl plugin list
The following compatible plugins are available:

/usr/local/bin/kubectl-graph
...
```

**Comment by jmorcar** [comment]
To visualize via cypher format What requirements I need? 

I have checked these:
* Install cypher-shell command
* A neo4j instance running via docker I see a fast command to test it with: 

`docker run --detach -p 7687:7687 -e NEO4J_AUTH=none neo4j:3.0 `

**Comment by steveteuber** [comment]
Sorry, I don't have any experience with running a local Neo4j database via docker.
I prefer to use the `Neo4j Desktop.app` installed via `brew cask install neo4j`.

**Comment by steveteuber** [comment]
@corneliusweig I think that sounds like a great idea. I will take a look into it!

But first things first, here is the pull request to add `kubectl-graph` to the `krew-index`:
https://github.com/kubernetes-sigs/krew-index/pull/773

**Comment by steveteuber** [comment]
The plugin is available via `krew`, so I will close this issue.

```
$ kubectl krew search graph
NAME   DESCRIPTION                                        INSTALLED
graph  Visualize Kubernetes resources and relationships.  yes
```
