### ISSUE TITLE
Support for ArangoDB

### ISSUE THREAD

**Issue by mysticaltech** [steveteuber/kubectl-graph#14]
Hey folks, amazing project! Please support [ArangoDB](https://www.arangodb.com/) / AQL for those of us not using Neo4j, thank you!

**Comment by lavrxxx** [comment]
@steveteuber Hey, interesting project! I also like ArangoDB and I want to try to implement this feature. Can I?

**Comment by steveteuber** [comment]
Hi @lavrxxx, my plan is to implement this output format during this week. But first I need to refactor some things.
And sure, why not? Pull requests are always welcome!

**Comment by lavrxxx** [comment]
Okay! I am just asking because may be you are already doing it. Then I will try.

**Comment by steveteuber** [comment]
Hey @mysticaltech and @lavrxxx.

I think I'm done. Please have a look if everything is working as expected.
Now you can upgrade the plugin to the latest version:

```
$ kubectl krew upgrade graph
Updated the local copy of plugin index.
  Upgrades available for installed plugins:
    * graph v0.3.1 -> v0.4.0
Upgrading plugin: graph
Upgraded plugin: graph
```
