### ISSUE TITLE
adjustable node size

### ISSUE THREAD

**Issue by icanhazbeer** [steveteuber/kubectl-graph#53]
is there a way to adjust the node size to fit the full resource name? it seems that when using dot format the name is truncated by '...' and I do not see the option to override this?

**Comment by steveteuber** [comment]
Hey @icanhazbeer,

Thank you for opening this issue. You are right, the name is truncated after 10 characters and currently it isn't possible to override this. But when you use SVG as output format (`dot -T svg ...`) you will get the full resource as a tooltip.

Is that's enough for you? If not or you prefer big nodes in the graph, please let me know.

**Comment by icanhazbeer** [comment]
Hi @steveteuber 
Apologies for the late reply.
I will try the tooltip but I would prefer to have some control over the size of the nodes.
I have some resources that have longer names (and some shorter ones) and I think it is better to see the full name inside the node.

**Comment by steveteuber** [comment]
Hi @icanhazbeer,

Could we close this issue or do you still miss something?

**Comment by a-27m** [comment]
Hi @steveteuber, thank you for the new `--truncate` param. I've just used it to make the graph nodes expand and hold the full resource names, just as requested, it seems.
